spring.datasource.url=jdbc:mysql://localhost:3306/oficina_mecanica?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
server.port=8080
spring.application.name=oficina-mecanica
spring.jpa.open-in-view=false